#pragma once

enum OBJECT_SELECT_TYPE { SHAPE, OBSTACLE, END };
enum OBJECT_TYPE { CUBE, PLAYER, ENEMY, BULLET, ITEM, SPHERE };
enum TEXTURE_TYPE { SPEED_UP, SPEED_DOWN, FROZEN, FOUR, FIVE, SIX, ITEM_NUM };